apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mvderby
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/Gin-G/mvderby.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mvderby
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
