apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mvderby
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/gin-g/mvderby
    newTag: sha-d70f2bb721ab6179dd665fb6d2d561a2bfce261a
