apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mvderby
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/gin-g/mvderby
    newTag: sha-9b47deadfcded78eb74d5bbf4b589207afe813b2
