apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mvderby
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/gin-g/mvderby
    newTag: sha-0f98689ef88aeab0562742aedd8c4aae30d3a0e1
